apiVersion: 1.0.0                                
previews:
- name: default                                   
  helm:
    chart: ./chart                  
    valuesFiles:                                 
    - ./chart/values.yaml
    values:                                      
      image:
        tag: ${{env.commit.shortSha}}
      ingress:
        annotations:
           kubernetes.io/tls-acme: "true"
           cert-manager.io/cluster-issuer: letsencrypt-prod
        hosts: 
          - host: ${{env.hostname}}
            paths:
              - path: /
                pathType: ImplementationSpecific
        tls:
          - secretName: ${{env.ingress.tlsSecretName}}
            hosts:
              - ${{env.hostname}}
    config:
      deployTimeout: "5m"  
- name: generated
  container:
    image: us-east1-docker.pkg.dev/core-workshop/workshop-registry/insurance-frontend:${{env.commit.shortSha}}
    ports:
    - value: 80
